[project]
name = "fixer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ebooklib>=0.18",
    "epubcheck>=5.1.0",
]

[dependency-groups]
dev = [
    "pdbpp>=0.10.3",
    "ruff>=0.8.2",
]
