[project]
name = "fixer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ebooklib>=0.18",
    "epubcheck>=5.1.0",
    "rich>=13.9.4",
]

[dependency-groups]
dev = [
    "pdbpp>=0.10.3",
    "pre-commit>=4.0.1",
]
