[project]
name = "epub_fixer"
version = "0.1.0"
description = "Makes OEBPS files into valid EPUB files"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "ebooklib>=0.18",
  "epubcheck>=5.1.0",
  "jpype1>=1.7.0",
  "rich>=13.9.4",
  "rich-click>=1.8.5",
]

[project.scripts]
epub_fixer = "epub_fixer.__main__:epub_fixer"

[dependency-groups]
dev = [
  "pdbpp>=0.10.3",
  "pytest>=9.0.3",
  "syrupy>=4.8.0",
]

[tool.ruff.lint]
select = ["I", "E", "F"]

[tool.uv]
package = true

[tool.uv.sources]
ebooklib = { git = "https://github.com/aerkalov/ebooklib" }
